from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l_aciklama = QtWidgets.QLabel(self.centralwidget)
        self.l_aciklama.setGeometry(QtCore.QRect(30, 240, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_aciklama.setFont(font)
        self.l_aciklama.setObjectName("l_aciklama")
        self.pte = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte.setGeometry(QtCore.QRect(30, 270, 271, 71))
        self.pte.setObjectName("pte")
        self.cB_marka = QtWidgets.QComboBox(self.centralwidget)
        self.cB_marka.setGeometry(QtCore.QRect(30, 390, 121, 31))
        self.cB_marka.setCurrentText("")
        self.cB_marka.setObjectName("cB_marka")
        self.cB_marka.addItem("")
        self.cB_marka.addItem("")
        self.cB_marka.addItem("")
        self.cB_marka.addItem("")
        self.cB_marka.addItem("")
        self.cB_marka.addItem("")
        self.cB_marka.addItem("")
        self.l_marka = QtWidgets.QLabel(self.centralwidget)
        self.l_marka.setGeometry(QtCore.QRect(30, 360, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_marka.setFont(font)
        self.l_marka.setObjectName("l_marka")
        self.l_kate = QtWidgets.QLabel(self.centralwidget)
        self.l_kate.setGeometry(QtCore.QRect(180, 360, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_kate.setFont(font)
        self.l_kate.setObjectName("l_kate")
        self.cb_kate = QtWidgets.QComboBox(self.centralwidget)
        self.cb_kate.setGeometry(QtCore.QRect(180, 390, 121, 31))
        self.cb_kate.setObjectName("cb_kate")
        self.cb_kate.addItem("")
        self.cb_kate.addItem("")
        self.cb_kate.addItem("")
        self.cb_kate.addItem("")
        self.cb_kate.addItem("")
        self.cb_kate.addItem("")
        self.cb_kate.addItem("")
        self.t_listele = QtWidgets.QTableWidget(self.centralwidget)
        self.t_listele.setGeometry(QtCore.QRect(330, 60, 731, 361))
        self.t_listele.setRowCount(30)
        self.t_listele.setColumnCount(7)
        self.t_listele.setObjectName("t_listele")
        self.t_listele.horizontalHeader().setVisible(True)
        self.btn_ekle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ekle.setGeometry(QtCore.QRect(30, 440, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_ekle.setFont(font)
        self.btn_ekle.setObjectName("btn_ekle")
        self.btn_sil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sil.setGeometry(QtCore.QRect(180, 440, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_sil.setFont(font)
        self.btn_sil.setObjectName("btn_sil")
        self.btn_guncelle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guncelle.setGeometry(QtCore.QRect(330, 440, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_guncelle.setFont(font)
        self.btn_guncelle.setObjectName("btn_guncelle")
        self.btn_listeleme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_listeleme.setGeometry(QtCore.QRect(480, 440, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_listeleme.setFont(font)
        self.btn_listeleme.setObjectName("btn_listeleme")
        self.btn_kate_list = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kate_list.setGeometry(QtCore.QRect(670, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_kate_list.setFont(font)
        self.btn_kate_list.setObjectName("btn_kate_list")
        self.l_kate_list = QtWidgets.QLabel(self.centralwidget)
        self.l_kate_list.setGeometry(QtCore.QRect(330, 20, 131, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_kate_list.setFont(font)
        self.l_kate_list.setObjectName("l_kate_list")
        self.cB_kate_list = QtWidgets.QComboBox(self.centralwidget)
        self.cB_kate_list.setGeometry(QtCore.QRect(470, 20, 171, 31))
        self.cB_kate_list.setObjectName("cB_kate_list")
        self.cB_kate_list.addItem("")
        self.cB_kate_list.addItem("")
        self.cB_kate_list.addItem("")
        self.cB_kate_list.addItem("")
        self.cB_kate_list.addItem("")
        self.cB_kate_list.addItem("")
        self.cB_kate_list.addItem("")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 70, 74, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.l_kod = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_kod.setFont(font)
        self.l_kod.setObjectName("l_kod")
        self.verticalLayout_1.addWidget(self.l_kod)
        self.l_ad = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_ad.setFont(font)
        self.l_ad.setObjectName("l_ad")
        self.verticalLayout_1.addWidget(self.l_ad)
        self.l_fiyat = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_fiyat.setFont(font)
        self.l_fiyat.setObjectName("l_fiyat")
        self.verticalLayout_1.addWidget(self.l_fiyat)
        self.l_miktar = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_miktar.setFont(font)
        self.l_miktar.setObjectName("l_miktar")
        self.verticalLayout_1.addWidget(self.l_miktar)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(110, 60, 191, 151))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lE_kod = QtWidgets.QLineEdit(self.widget1)
        self.lE_kod.setObjectName("lE_kod")
        self.verticalLayout_2.addWidget(self.lE_kod)
        self.lE_ad = QtWidgets.QLineEdit(self.widget1)
        self.lE_ad.setObjectName("lE_ad")
        self.verticalLayout_2.addWidget(self.lE_ad)
        self.lE_fiyat = QtWidgets.QLineEdit(self.widget1)
        self.lE_fiyat.setObjectName("lE_fiyat")
        self.verticalLayout_2.addWidget(self.lE_fiyat)
        self.lE_miktar = QtWidgets.QLineEdit(self.widget1)
        self.lE_miktar.setObjectName("lE_miktar")
        self.verticalLayout_2.addWidget(self.lE_miktar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cB_marka.setCurrentIndex(-1)
        self.cb_kate.setCurrentIndex(-1)
        self.cB_kate_list.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l_aciklama.setText(_translate("MainWindow", "Ürün Açıklaması:"))
        self.cB_marka.setItemText(0, _translate("MainWindow", "marka_1"))
        self.cB_marka.setItemText(1, _translate("MainWindow", "marka_2"))
        self.cB_marka.setItemText(2, _translate("MainWindow", "marka_3"))
        self.cB_marka.setItemText(3, _translate("MainWindow", "marka_4"))
        self.cB_marka.setItemText(4, _translate("MainWindow", "marka_5"))
        self.cB_marka.setItemText(5, _translate("MainWindow", "marka_6"))
        self.cB_marka.setItemText(6, _translate("MainWindow", "marka_7"))
        self.l_marka.setText(_translate("MainWindow", "Ürün Markası:"))
        self.l_kate.setText(_translate("MainWindow", "Ürün Kategori:"))
        self.cb_kate.setItemText(0, _translate("MainWindow", "kategori_1"))
        self.cb_kate.setItemText(1, _translate("MainWindow", "kategori_2"))
        self.cb_kate.setItemText(2, _translate("MainWindow", "kategori_3"))
        self.cb_kate.setItemText(3, _translate("MainWindow", "kategori_4"))
        self.cb_kate.setItemText(4, _translate("MainWindow", "kategori_5"))
        self.cb_kate.setItemText(5, _translate("MainWindow", "kategori_6"))
        self.cb_kate.setItemText(6, _translate("MainWindow", "kategori_7"))
        self.btn_ekle.setText(_translate("MainWindow", "Ürün Ekle"))
        self.btn_sil.setText(_translate("MainWindow", "Ürün Sil"))
        self.btn_guncelle.setText(_translate("MainWindow", "Ürün Güncelleme"))
        self.btn_listeleme.setText(_translate("MainWindow", "Ürün Listeleme"))
        self.btn_kate_list.setText(_translate("MainWindow", "Kategoriye Göre Listeleme"))
        self.l_kate_list.setText(_translate("MainWindow", "Kategoriye göre Listele"))
        self.cB_kate_list.setItemText(0, _translate("MainWindow", "kategori_1"))
        self.cB_kate_list.setItemText(1, _translate("MainWindow", "kategori_2"))
        self.cB_kate_list.setItemText(2, _translate("MainWindow", "kategori_3"))
        self.cB_kate_list.setItemText(3, _translate("MainWindow", "kategori_4"))
        self.cB_kate_list.setItemText(4, _translate("MainWindow", "kategori_5"))
        self.cB_kate_list.setItemText(5, _translate("MainWindow", "kategori_6"))
        self.cB_kate_list.setItemText(6, _translate("MainWindow", "kategori_7"))
        self.l_kod.setText(_translate("MainWindow", "Ürün Kodu:"))
        self.l_ad.setText(_translate("MainWindow", "Ürün Adı:"))
        self.l_fiyat.setText(_translate("MainWindow", "Birim Fiyat:"))
        self.l_miktar.setText(_translate("MainWindow", "Stok Miktarı:"))
